### ISSUE TITLE
Payload Class missing for notifications about emailed invoices

### ISSUE THREAD

**Issue by fireleaf-solutions** [davidsneighbour/booka-issues#114]
.../agencies/email_invoice/?invoice=1

**Comment by davidsneighbour** [comment]
- is the email sent or not?
- is your Sendgrid API key set up properly?
- is your Sendgrid account fully configured or are they waiting on some verification? In that case the API key might not work yet.

the API key needs rights to send emails. obviously.

**Comment by davidsneighbour** [comment]
Error: 

Fatal error: Uncaught Error: Class 'Boka10\Users\Payloads\PayloadInvoicing' not found in /home/patrick/Projects/BooKa/app/src/Boka10/Invoicing/InvoicingListener.php on line 53
Error: Class 'Boka10\Users\Payloads\PayloadInvoicing' not found in /home/patrick/Projects/BooKa/app/src/Boka10/Invoicing/InvoicingListener.php on line 53
