### ISSUE TITLE
Double fields for mobile phone and email in booking form

### ISSUE THREAD

**Issue by HDsamui** [davidsneighbour/booka-issues#117]
in booking form two fields are shown twice and if one field is empty then data loss. sad.

**Comment by davidsneighbour** [comment]
For this to be fixed we need to add mobile and email fields to the top section of the voucher. After that it's just removing it from custom field setup.

**Comment by davidsneighbour** [comment]
Added fields to voucher header in davidsneighbour/booka@bb14b3107d86

**Comment by davidsneighbour** [comment]
in deploy.
