### ISSUE TITLE
Invoice Receipts No Values

### ISSUE THREAD

**Issue by fireleaf-solutions** [davidsneighbour/booka-issues#142]
Please check the invoice receipts.
They can be created and show, but there are no values - see screenshot
https://fireleaf.inkohsamui.com/agencies/receipt-print/

<img width="1272" alt="Screen Shot 2020-01-03 at 12 32 16" src="https://user-images.githubusercontent.com/53209664/71708629-569cb680-2e25-11ea-95cc-0dd878d20578.png">

**Comment by davidsneighbour** [comment]
bill/receipt does not receive bookings connected to the invoice in question which leaves the receipt empty.

**Comment by davidsneighbour** [comment]
I pushed v11.9.86 with the hotfix from #143 to your stage. Please test if that solves the issue.
