### ISSUE TITLE
Edit agency not saved

### ISSUE THREAD

**Issue by fireleaf-solutions** [davidsneighbour/booka-issues#195]
Opening an existing Agency to edit, sets the Agency Group to Owner Agency by default.
Also, when a new Agency is created and the Agency Group set to whatever agency group and the entry is saved, it is saved as "Owner Agency" regardless of what has been set as Agency Group at the time of setup.

https://fireleaf.inkohsamui.com/agencies/edit/5/

**Comment by davidsneighbour** [comment]
Agency form is not saved on submission (request is pre-empted so nothing is saved).
