### ISSUE TITLE
Taxes to allow Decimals

### ISSUE THREAD

**Issue by fireleaf-solutions** [davidsneighbour/booka-issues#225]
WHT currently doesn't allow decimals

<img width="968" alt="Screen Shot 2020-07-03 at 14 44 01" src="https://user-images.githubusercontent.com/53209664/86445434-8e38dc80-bd3c-11ea-8394-eb9b6ca8e63c.png">

**Comment by davidsneighbour** [comment]
Field API has a parameter steps for the float field. Setting it to second after comma decimals for both, WHT and VAT.
This will probably have impact further down the road in the display of these values. Zeroes at the end should be hidden. There is a ticket in the private Booka repo open for this.
